/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectGradle.model;

import org.junit.Test;
import static org.junit.Assert.*;

public class MediumModelTesting {
	// testing if we get the degrees 
    @Test 
    public void mediumDegreeTest() {
        MediumModel m = new MediumModel();
		assertNotNull("it should return the arraylist of degrees", m.mediumDegree());
    }
    
    // checking the length of the arraylist
     @Test 
    public void mediumDegreeTestSize() {
        MediumModel m = new MediumModel();
		assertEquals("size of the array is 12",m.mediumDegree().size(),12);
    }
    
    // checking the degree is 90 of the arraylist
     @Test 
    public void mediumDegreeTest90Degrees() {
        MediumModel m = new MediumModel();
		assertEquals("check if the degree is 90 degrees ",m.mediumDegree().get(6),90);
    }
    
    // checking the degree is 0 of the arraylist
     @Test 
    public void mediumDegreeTest0Degrees() {
        MediumModel m = new MediumModel();
		assertEquals("check if the degrees is 0 ",m.mediumDegree().get(0),0);
    }
    
    // check if we get the boolean arraylist
    @Test
    public void mediumBooleanTest(){
		MediumModel m = new MediumModel();
		assertNotNull("it should return the arraylist of booleans", m.mediumBoolean());
	}
	
	// check if we get the boolean true 
    @Test
    public void mediumBooleanTestTrue(){
		MediumModel m = new MediumModel();
		assertEquals("it should return the booleans true", m.mediumBoolean().get(6),true);
	}
	
	// check if we get the boolean false 
    @Test
    public void mediumBooleanTestFalse(){
		MediumModel m = new MediumModel();
		assertEquals("it should return the booleans false", m.mediumBoolean().get(7),false);
	}
	
	// check if get the imageIcons ArrayList
    @Test
    public void mediumImageTest(){
		MediumModel m = new MediumModel();
		assertNotNull("get the image icon arraylist", m.mediumImage());
	}
	
	// check if get the JLabel ArrayList
    @Test
    public void mediumLableTest(){
		MediumModel m = new MediumModel();
		assertNotNull("get the image icon arraylist", m.mediumLable());
	}
	
}
